openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App API
  description: API for managing contacts, authentication, password reset, and photos.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Contacts
    description: Operations on contacts
  - name: Auth
    description: Authentication and session management
servers:
  - url: http://localhost:3000
  - url: https://hw7-swagger-p4b0.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/path/contacts/get.yaml'
    post:
      $ref: '../swagger/path/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/path/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/path/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/path/contacts/{id}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
